### ISSUE TITLE
Php artisan hatası

### ISSUE THREAD

**Issue by mrtsglk** [trker/VoyagerAwesomeAlbums#1]
Kurulumdan sonra serve komutunu tekrar başlattığımda

Type error: Argument 2 passed to Illuminate\Routing\UrlGenerator::__construct() must be an instance of Illuminate\Http\Request, null given, called in /var/www/html/cost/vendor/laravel/framework/src/Illuminate/Routing/RoutingServiceProvider.php on line 67 

Hatası alıyorum.

**Comment by trker** [comment]
@mrtsglk geri dönüşünüz için teşekkürler sorunun farkındayım homestead üzerinden çalıştığım ve homestead te sorun u farketmediğim  için paketi eklemiştim fakat namespace ler ile ilgili bir sorun oldugu için consol komutlarında soruna neden oluyor  en kısa sürede güncellemesini yapıcam bilginize.

**Comment by trker** [comment]
@mrtsglk  Sorunları çözdüm tekrar denemek istersen

**Comment by mrtsglk** [comment]
@trker teşekkür ederim o proje için geçici bir çözüm bulmuştum. Artık bir sonrakinde tekrar kullanacağım.
